# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.1
loader_version=0.18.4
# Mod Properties
mod_version=2.4.1
maven_group=com.kevin
archives_base_name=TierTagger
# Dependencies
# check this on https://modmuss50.me/fabric.html
ukulib_version=2.0.0+26.1
fabric_api_version=0.144.3+26.1
devauth_version=1.2.2